# Generated by Django 4.2.3 on 2023-07-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0004_fotografia_data_publicacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="foto",
            field=models.ImageField(blank=True, upload_to="fotos/%Y/%m/%d/"),
        ),
    ]
