# Generated by Django 4.2.3 on 2023-07-29 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0005_alter_fotografia_foto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fotografia",
            old_name="descrição",
            new_name="descricao",
        ),
    ]
